export const DIRECTORY_SHOPS = [
  { shopId: '100030', name: 'All Season Balagere', place: 'Balagere' },
  { shopId: '100061', name: 'All Season Hmt', place: '' },
  { shopId: '100027', name: 'All Season Panathur', place: 'Panathur' },
  { shopId: '100031', name: 'All Season Supermart Gunjur', place: '' },
  { shopId: '100054', name: 'All Season Vidhyaranyapura', place: '' },
  { shopId: '100051', name: 'Best Mart Hyper Market', place: '' },
  { shopId: '100052', name: 'Brigade Hyper Mart Kalkere', place: '' },
  { shopId: '100029', name: 'Brigade Hypermarket Hennur Bagalur Main Rd', place: '' },
  { shopId: '100037', name: 'Brigade Supermart Bileshivale', place: '' },
  { shopId: '100040', name: 'City Pearl Supermarket Horamavu', place: '' },
  { shopId: '100024', name: 'Dream Mart Megastore Hoskote', place: '' },
  { shopId: '100057', name: 'Easy Shoping Mart Dodda Kammanahalli', place: '' },
  { shopId: '100022', name: 'Families Hypermart Chikkabasavanapura', place: 'K R Puram' },
  { shopId: '100041', name: 'Families Hypermart Sonnenahalli', place: '' },
  { shopId: '100056', name: 'Families Thejaswini Nagar', place: '' },
  { shopId: '100058', name: 'Family Bigmart Attibele', place: '' },
  { shopId: '100055', name: 'Family Hyper Market Chandapura', place: '' },
  { shopId: '100034', name: 'Freshco Hyperbazaar Reliable Tranquil Layout', place: '' },
  { shopId: '100035', name: 'Freshco Hyperbazaar Somasundarapalya', place: '' },
  { shopId: '100000', name: 'Greens Fresh Arekere', place: '' },
  { shopId: '100049', name: 'Maha Bazar Bel Road', place: '' },
  { shopId: '100043', name: 'Market Fresh Jyotipuram', place: '' },
  { shopId: '100048', name: 'Market Fresh Supermarket Mallasandra', place: '' },
  { shopId: '100025', name: 'Million Mart Yelahanka Hobli', place: 'Hegdenagar' },
  { shopId: '100023', name: 'Mythri Mart Btm 1st Stage', place: '' },
  { shopId: '100059', name: 'Plus Point Hyper Market Harlur Main Road', place: '' },
  { shopId: '100026', name: 'Rolla Hyper Market Begur', place: 'Begur' },
  { shopId: '100042', name: 'Rolla Hypermarket Seegehalli', place: '' },
  { shopId: '100050', name: 'Maha Bazar Sadashiva Nagar', place: '' },
  { shopId: '100032', name: 'Season Fresh Varthur', place: '' },
  { shopId: '100045', name: 'Seven Days Kyalasanahalli', place: '' },
  { shopId: '100044', name: 'Shoprite', place: '' },
  { shopId: '100060', name: 'Topmart Supermarket Krpuram', place: '' },
];
